name: polyassistant
description: "Application de ressources pédagogiques pour étudiants"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_web_auth: ^0.5.0
  http: ^1.2.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  firebase_messaging: ^15.0.5
  flutter_local_notifications: ^17.2.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  flutter_appauth: ^6.0.6
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_pdfviewer: ^23.1.44
  open_file: ^3.5.10
  shimmer: ^2.0.0
  package_info_plus: ^9.0.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/resources/
    - assets/resources_manifest.json
    - assets/resources_manifest_github.json
    - assets/resources_manifest_online.json