// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxblJprbNN2TBPWiFDdbQhySyfAS52es',
    appId: '1:39495723329:web:39625f8b1e91e708a159c0',
    messagingSenderId: '39495723329',
    projectId: 'polyassistant-d250a',
    authDomain: 'polyassistant-d250a.firebaseapp.com',
    storageBucket: 'polyassistant-d250a.firebasestorage.app',
    measurementId: 'G-MVB5XSJG2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25t9OVxlhHPmn97b4WykHKIqEbE2RaOY',
    appId: '1:39495723329:android:f351f759dc805d14a159c0',
    messagingSenderId: '39495723329',
    projectId: 'polyassistant-d250a',
    storageBucket: 'polyassistant-d250a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACZNn7BfsFmkJqqhb1cbxH0Qminzn3mhs',
    appId: '1:39495723329:ios:c83634793ca0b397a159c0',
    messagingSenderId: '39495723329',
    projectId: 'polyassistant-d250a',
    storageBucket: 'polyassistant-d250a.firebasestorage.app',
    iosBundleId: 'com.example.polyassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACZNn7BfsFmkJqqhb1cbxH0Qminzn3mhs',
    appId: '1:39495723329:ios:c83634793ca0b397a159c0',
    messagingSenderId: '39495723329',
    projectId: 'polyassistant-d250a',
    storageBucket: 'polyassistant-d250a.firebasestorage.app',
    iosBundleId: 'com.example.polyassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHxblJprbNN2TBPWiFDdbQhySyfAS52es',
    appId: '1:39495723329:web:80fafac12753d416a159c0',
    messagingSenderId: '39495723329',
    projectId: 'polyassistant-d250a',
    authDomain: 'polyassistant-d250a.firebaseapp.com',
    storageBucket: 'polyassistant-d250a.firebasestorage.app',
    measurementId: 'G-DTD2PQH83G',
  );
}
